openapi: 3.0.0
info:
  title: RAG Chatbot Backend API
  version: 1.0.0
paths:
  /api/chat-selected:
    post:
      summary: Get explanation for selected text
      operationId: explainSelectedText
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - question
                - selected_text
              properties:
                question:
                  type: string
                  description: The user's question about the selected text.
                  example: "Explain this concept."
                selected_text:
                  type: string
                  description: The text snippet selected by the user from the book.
                  example: "ROS 2 is a middleware..."
      responses:
        '200':
          description: Successful response with explanation.
          content:
            application/json:
              schema:
                type: object
                properties:
                  answer:
                    type: string
                    description: The explanation based only on the selected text.
                    example: "This text explains..."
                  sources:
                    type: array
                    items:
                      type: string
                    description: An empty list of sources, as explanation is from provided text.
                    example: []
        '400':
          description: Bad Request - Invalid input (e.g., empty selected text).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error - API failures (OpenAI/Gemini).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '503':
          description: Service Unavailable - External language model service rate limit exceeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: A descriptive error message.
          example: "Selected text cannot be empty."
